#!/bin/sh

# Add Autostatic PPA, and update, if necessary
if [ -f /etc/apt/sources.list.d/autostatic-audio-raspbian.list ];
then
    echo "autostatic PPA already here. Not adding...";
else
    wget -q -O - http://rpi.autostatic.com/autostatic.gpg.key | sudo apt-key add -
    sudo wget -q -O /etc/apt/sources.list.d/autostatic-audio-raspbian.list http://rpi.autostatic.com/autostatic-audio-raspbian.list
    sudo apt-get update
fi



# SooperLooper
if [ -f /usr/bin/sooperlooper ];
then
    echo "SooperLooper already installed."
else
    sudo apt-get install -y sooperlooper
fi

# MidiDings
if [ -f /usr/bin/mididings ];
then
    echo "mididings already installed."
else
    sudo apt-get install -y mididings
fi


# Need to modify some real-time audio settings.
# Note - rtprio should end up being 84 (not 99).
# TODO - might have to patch /etc/security/limits.d/audio.conf
# "-p critical" is my attempt at silent execution that won't 
# wait for user prompt.
if [ -f /etc/security/limits.d/audio.conf ]; then
    echo "Real-time audio already enabled."
else
    sudo dpkg-reconfigure -p critical jackd1
    # Add pi user to audio group:
    sudo usermod -a -G audio pi
fi

# Configure the RPI to auto-login as "pi" and then add the audio
# launcher script (rpi-audio) to the pi user's ~/.profile.

# inittab for auto-login
if grep -q "1:2345:respawn:/bin/login" /etc/inittab; then
    echo "/etc/inittab already modified for auto-login"
else
    sudo cp /etc/inittab /etc/inittab.bak
    sudo sed 's/1:2345:respawn:\/sbin\/getty.*$/1:2345:respawn:\/bin\/login -f pi tty1 <\/dev\/tty1 >\/dev\/tty1 2>\&1/' /etc/inittab | sudo tee /etc/inittab.new
    sudo mv /etc/inittab.new /etc/inittab
fi

# modify .profile to include launcher
if grep -q "rpi-audio" /home/pi/.profile; then
    echo ".profile already includes rpi-audio launcher"
else
    echo "Adding rpi-audio launcher to tail of ~/.profile..."
    echo "/home/pi/rpi-music/looper/rpi-audio start >> /home/pi/rpi-music/looper/rpi-audio.log 2>&1 &" >> /home/pi/.profile
fi

echo "rpi-audio setup complete."

